// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSIE1rVEhki1bnLw7Xerl50GWPvMvd6KI',
    appId: '1:633271156310:web:94439890995504595245f7',
    messagingSenderId: '633271156310',
    projectId: 'harmony-f35b9',
    authDomain: 'harmony-f35b9.firebaseapp.com',
    storageBucket: 'harmony-f35b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRElLJYPgoRv5gzRxO10XrkyJYq47i98',
    appId: '1:633271156310:android:2fe2d1cc908ff1ab5245f7',
    messagingSenderId: '633271156310',
    projectId: 'harmony-f35b9',
    storageBucket: 'harmony-f35b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ORk6i4iWZzBNzH_VDsmRbUHjN_adAwA',
    appId: '1:633271156310:ios:592d09ddb7ca467e5245f7',
    messagingSenderId: '633271156310',
    projectId: 'harmony-f35b9',
    storageBucket: 'harmony-f35b9.firebasestorage.app',
    iosBundleId: 'com.example.harmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSIE1rVEhki1bnLw7Xerl50GWPvMvd6KI',
    appId: '1:633271156310:web:d27903bdf79f54fd5245f7',
    messagingSenderId: '633271156310',
    projectId: 'harmony-f35b9',
    authDomain: 'harmony-f35b9.firebaseapp.com',
    storageBucket: 'harmony-f35b9.firebasestorage.app',
  );
}
